# Change these first
owner: jason-xy # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository

sites:
  - name: UAV-Group Website
    url: https://uav.hkust.edu.hk
  - name: UAV-Group NAS
    url: https://dsm.hkust-uav.org
  - name: Personal NAS - frpc
    url: yxuew.xyz
    port: 9443
    check: "tcp-ping"
  - name: Personal NAS - ugid
    url: https://zyh-xy.aar4.ug.link
  - name: Personal Website
    url: https://jason-xy.cn
  - name: Proxy Server
    url: https://a.yxuew.xyz
  - name: RustDesk Server
    url: rustdesk.yxuew.xyz
    port: 21116
    check: "tcp-ping"

assignees:
  - jason-xy

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: jason-xy.cn/upptime
  # baseUrl: /your-repo-name
  logoUrl: https://avatars.githubusercontent.com/u/53471811?v=4
  name: Yang Xu's Uptime Monitor
  introTitle: "Uptime Monitor for Daily Services"
  introMessage: "Monitoring the status of my personal and group services."
  theme: ocean
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
